sudo: false
env:
  - NODE_VERSION=0.12
  - NODE_VERSION=4.0
  - NODE_VERSION=4.1
  - NODE_VERSION-4.2
  - NODE_VERSION=5

before_install:
  - "npm config set spin false"

os:
  - osx
  - linux

script: npm test

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - npm install
